//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawCatalog1718
    {
        public string Subject { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Hours { get; set; }
        public string Offered { get; set; }
        public string Prerequisites { get; set; }
        public string Corequisites { get; set; }
        public string Requirements { get; set; }
        public string Recommendations { get; set; }
        public string GE { get; set; }
        public string SameAs { get; set; }
    }
}
